### ISSUE TITLE
misunderstand in script.yaml

### ISSUE THREAD

**Issue by CloudHoang90** [TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#1]
Hi TommerFi,
Thanks for sharing your code but as your guide to config the script.yaml, I cannot understand what to do with this.

> living_room_rm_pro_send_packet:
>   sequence:
>     - service: switch.broadlink_send_packet_XXX_XXX_XXX_XXX
>       data_template:
>         packet:
>           - '{{ packet_code }}

If you can, please explain more about that or just send me your code as example.
Thanks

**Comment by TomerFi** [comment]
Sure. This is the flow:

For this example lets say the collected AC controller states are:
- `Mode: HEAT`
- `Fan: LOW`
- `Temperature: 28`

1.  This [automation](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#run-scripts-for-power-on) is triggered when the [power controller](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#power-control) change its state to `on`. It collects the states of the [fan controller](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#fan-control), [mode controller](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#mode-control) and the [temperature controller](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#temperature-control) and passes them to the next script. 

2. This [script](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#choose-the-correct-ir-packet-constructor-script) gets the call and based on the `mode` and `fan` passed in by the previous `automation`. It the calls the next script passing on the `temperature`.

3.  Based on our example this [script](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#mode-heat-and-fan-low) will get the call. It will choose the correct IR packet based on the `temperature` received by the previous script. It then will call the next script passing the chosen IR packet to it.

4.  The last [script](https://github.com/TomerFi/home_assistant_custom_ac_alexa_smarthome_skill#send-ir-packets-to-broadlink-script), which is the one you are asking about will receive the call and send the incoming IR packet to the designated Broadlink device.

I have my own configuration shared on my [here](https://github.com/TomerFi/my_home_assistant_configuration) too,
You can check it out and see an example of this process.

**Comment by CloudHoang90** [comment]
Thank for your help.
with your explain and sample code, I will try as best as I can do make it work...

Thanks for your share again :)

**Comment by TomerFi** [comment]
My pleasure!
If you need anything else feel free to ask, I'll do my best to try and help.

**Comment by CloudHoang90** [comment]
Hi TomerFi,
I just try again and make your code show up on my HASS. Really happy with this.

However when I try to test with my Broadlink RM Pro+, it's not work :(
I look back the code I saw that there are missing the service to send the IR code for power on the Aircon.

Moreover, I trying to power on my Aircon and change the MODE + temp. The AC switch not switch to ON and there are nothing with my Aircon.
Trying to catch the log and I found this error

> 2018-03-09 01:15:00 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sensor.date__time=2018-03-09, 01:14; friendly_name=Date & Time, icon=mdi:calendar-clock @ 2018-03-09T01:14:01.458748+07:00>, new_state=<state sensor.date__time=2018-03-09, 01:15; friendly_name=Date & Time, icon=mdi:calendar-clock @ 2018-03-09T01:15:00.622450+07:00>, entity_id=sensor.date__time>
> 2018-03-09 01:15:02 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sensor.processor_use=4; friendly_name=Processor use, icon=mdi:memory, unit_of_measurement=% @ 2018-03-09T01:14:32.540982+07:00>, new_state=<state sensor.processor_use=7; friendly_name=Processor use, icon=mdi:memory, unit_of_measurement=% @ 2018-03-09T01:15:02.692807+07:00>, entity_id=sensor.processor_use>
> 2018-03-09 01:15:02 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sensor.memory_free=797.3; friendly_name=Memory free, icon=mdi:memory, unit_of_measurement=MiB @ 2018-03-09T01:14:32.505110+07:00>, new_state=<state sensor.memory_free=794.4; friendly_name=Memory free, icon=mdi:memory, unit_of_measurement=MiB @ 2018-03-09T01:15:02.734889+07:00>, entity_id=sensor.memory_free>
> 2018-03-09 01:15:30 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sun.sun=below_horizon; friendly_name=Sun, next_rising=2018-03-08T23:04:12+00:00, azimuth=71.19, next_dusk=2018-03-09T11:25:02+00:00, next_noon=2018-03-09T05:04:04+00:00, next_dawn=2018-03-08T22:43:06+00:00, next_midnight=2018-03-09T17:03:46+00:00, next_setting=2018-03-09T11:03:56+00:00, elevation=-71.38 @ 2018-03-09T01:03:18.665136+07:00>, new_state=<state sun.sun=below_horizon; friendly_name=Sun, next_rising=2018-03-08T23:04:12+00:00, azimuth=71.46, next_dusk=2018-03-09T11:25:02+00:00, next_noon=2018-03-09T05:04:04+00:00, next_dawn=2018-03-08T22:43:06+00:00, next_midnight=2018-03-09T17:03:46+00:00, next_setting=2018-03-09T11:03:56+00:00, elevation=-71.15 @ 2018-03-09T01:03:18.665136+07:00>, entity_id=sun.sun>
> 2018-03-09 01:15:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sensor.processor_use=7; friendly_name=Processor use, icon=mdi:memory, unit_of_measurement=% @ 2018-03-09T01:15:02.692807+07:00>, new_state=<state sensor.processor_use=0; friendly_name=Processor use, icon=mdi:memory, unit_of_measurement=% @ 2018-03-09T01:15:33.702247+07:00>, entity_id=sensor.processor_use>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=open_cover, service_data=entity_id=cover.lr_ac_temp_cover, service_call_id=1972009904-14, domain=cover>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.helpers.script] Running script
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.helpers.script] Executing step call service
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service=set_value, service_data=value=18, entity_id=input_text.lr_ac_temp_text, service_call_id=1972009904-15, domain=input_text>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state input_text.lr_ac_temp_text=17; friendly_name=lr_ac_temp_text, min=0, mode=text, pattern=None, name=lr_ac_temp_text, hidden=True, max=100 @ 2018-03-09T01:14:50.061466+07:00>, new_state=<state input_text.lr_ac_temp_text=18; friendly_name=lr_ac_temp_text, min=0, mode=text, pattern=None, name=lr_ac_temp_text, hidden=True, max=100 @ 2018-03-09T01:15:44.754572+07:00>, entity_id=input_text.lr_ac_temp_text>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state sensor.lr_ac_temp_sensor=17; friendly_name=Current Temperature, icon=mdi:thermometer @ 2018-03-09T01:14:50.067250+07:00>, new_state=<state sensor.lr_ac_temp_sensor=18; friendly_name=Current Temperature, icon=mdi:thermometer @ 2018-03-09T01:15:44.768070+07:00>, entity_id=sensor.lr_ac_temp_sensor>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=1972009904-15>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state cover.lr_ac_temp_cover=open; friendly_name=Change Temperature, icon=mdi:temperature-celsius, current_position=17.0, supported_features=3 @ 2018-03-09T01:14:47.351869+07:00>, new_state=<state cover.lr_ac_temp_cover=open; friendly_name=Change Temperature, icon=mdi:temperature-celsius, current_position=18.0, supported_features=3 @ 2018-03-09T01:14:47.351869+07:00>, entity_id=cover.lr_ac_temp_cover>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.components.automation] Executing lr_ac_changes
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event logbook_entry[L]: name=lr_ac_changes, domain=automation, entity_id=automation.lr_ac_changes, message=has been triggered>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.helpers.script] Script lr_ac_changes: Running script
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.helpers.script] Script lr_ac_changes: Test condition state: False
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state automation.lr_ac_changes=on; friendly_name=lr_ac_changes, id=lr_ac_changes, hidden=True, last_triggered=2018-03-09T01:14:50.086393+07:00 @ 2018-03-09T01:03:21.679502+07:00>, new_state=<state automation.lr_ac_changes=on; friendly_name=lr_ac_changes, id=lr_ac_changes, hidden=True, last_triggered=2018-03-09T01:15:44.820322+07:00 @ 2018-03-09T01:03:21.679502+07:00>, entity_id=automation.lr_ac_changes>
> 2018-03-09 01:15:44 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=1972009904-14>

Did I do sthing wrong??? Can you help me? 
Really thanks for that!

**Comment by TomerFi** [comment]
I can't quite see an error here.
Can you share your `yamls` so I can have a look?

**Comment by CloudHoang90** [comment]
Please download my yamls following the link https://drive.google.com/open?id=1sAtOrvuoW0TLSELUKQD-Vg6Zx7bS0Mri

**Comment by TomerFi** [comment]
What is you HA version?

**Comment by CloudHoang90** [comment]
lasttime I used is 0.63
I upgraded lastnight and now is 0.64.x

**Comment by TomerFi** [comment]
Well your yaml configuration looks ok.
 When nothing happened on you broadlink device,
What were the values (states) on the following entities:
- input_select.lr_ac_state
- input_select.lr_ac_fan
- sensor.lr_ac_temp_sensor

Please note, your `switches.yaml` is showing your mac addresses, I would suggest to delete the zip files from you google drive.

**Comment by CloudHoang90** [comment]
Hi @TomerFi 
I just recheck all the yamls and there are some mistake on input_select.
But now I outside so I cannot check it work or not.

However, as I ask before, your script not call the Power On packet?
I dont know what current Aircon are you using but mine must press power on first then to modify the mode and temp.

**Comment by TomerFi** [comment]
That might be the reason for it not working.
This design is for standard IR AC units that receive packets containing all the required information in one packet:
- Power: ON
- Mode: HEAT
- Fan: LOW
- Temperature: 25

If your unit works differently and expects a separate packet for `Power: ON` and a separate packet for the rest of the configuration, Then this won't work for you and you'll have to customized it for your own needs.

The fastest way for you to go in this case I think is editing all of the `IR packet selection scripts` so that they'll send the `ON` packet before sending the seconds packet.
Maybe try something like this (edited from your `scripts.yaml` file):
```yaml
##Mode: COOL and Fan: AUTO
living_room_ac_cool_auto_script:
  sequence:
    - service: script.living_room_rm_pro_send_packet
      data:
        packet_code: "place your on packet here"
    - service: script.living_room_rm_pro_send_packet
      data_template:
        packet_code: >
          {% if (selected_temp == "16") %} "JgC8AXQ4DwwQKRAMEA0PDQ8MEAwQDBANDw0PDg8NDwwQKRAMEA0PDQ8MEAwQDBANDyoPKRApEAwQDQ8qDwwQDA0PEA0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PDQ8MECkQKRANDw0PDBAMEAwQAAFHdDgPDBApEQwPDQ8MEAwQDBANDwwQDBAMEA0PDQ8pEAwQDBANDw0PDBAMEAwQKg8pECkQDBANDyoPDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDBAqDwwQDBApECoPKg8MEAwQDBANDw0PDBAMECkQDQ8NDwwQDBANDw0PDBAMDg4QKg8pECkQKRApEA0PKRAMECkQDQ8MEAwQKg8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBANDyoPKRApEAwQDQ8NDwwQDBAMEAwQDQ8NDykQKRApEA0PDBAMDg4QDQ8NDwwQDQ8NDwwQDBAMEA0PDQ8MEAwQKRANDwwQDBAMEA0PDQ8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDBAMEAwQKg8NDykQDBAMEA0PDBAMEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "17") %} "gC8AXU3EAwQKRANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PKg8MEAwQDBANDw0PDBAMECoQKg8pEAwQDBApEA0PDBAMEAwQDBANDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PDQ8MEAwQDBAMEA0PDQ8MEAwQDQ8NDykQKQ0PEA0PDQ8MEAwQAAFGdTgPDQ8pEAwQDBANDw0PDBAMEAwQDQ8MEAwQDBAqDwwQDBANDwwQDBAMEA0PKg8pECkQDBANDyoPDBAMDQ8QDQ8NDwwQDBANDw0PDBAMEA0PDQ8pEAwQDBAqDykQKRAMEA0PDQ8pEAwODhANDyoPDBAMEAwQDQ8NDwwQDBANDw0PKRApECkQKRAqDwwQKRAMECoPDQ8MEAwQKRANDw0PDBAMEAwQDQ8MEAwQDBANDw0PDQ8MECkQKRAqDw0PDBAMEA0PDQ8NDwwQDBAMECoPKRApEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEAwQKg8NDwwQDBAMEA0PDBApEAwQDQ8NDwwQDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQKRAqDykQDBANDwwQDBAMEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "18") %} "JgC8AXQ3EA0PKRAMEA0PDQ8MEAwQDBANDw0PDBAMEAwQKg8NDwwQDBANDw0PDBAMECkQKg8qDwwQDBArDwwQDQ8NDwwQDBAMEA0PDQ8NDwwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDBAMEAwQDQ8NDwwQDA8NECoPKRAMEAwQDQ8MEAwQAAFHdDgPDBApEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8qDwwQDBAMEA0PDQ8MEAwQKRAqDykQDBAMECoPDQ8MEAwQDBANDw0PDBAMEAwQDQ8MEAwQDBAqDw0PDBApECkQKg8NDwwQDBAMECoPDBAMECkQDQ8NDwwQDBAMEA0PDBAMEAwQKg8qDykQKQ4rEA0PKRAMECkQDBANDwwQKRAMEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PDQ8MECkQKRAqDwwQDBAMEA0PDBANDw0PDBAMECoPKg8pEAwQDBANDw0PDBAMEA0PDBAMEA0PDQ8MEAwQDBANDw0PKRAMEAwQDQ8NDwwQDBApEA0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEA0PDRANDw0PKRAMDg4QKg8NDwwQDBANDwANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "19") %} "JgC8AXU3EAwQKg8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQKRAMEA0PDQ8MEAwPDRANDykQKRApEA0PDQ8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PDQ8MEAwPDRANDw0PDQ8MECkQKRANDw0PDBAMEA0PAAFHdDcQDBApEA0PDQ8MEAwQDBANDw0PDBAMEAwQDQ8pEAwQDBANDw0PDBAMEAwQKg8pECkQDBANDykQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PDBApEA0PDQ8pECkQKRANDw0PDBApECkQDQ8NDykQDBAMEA0PDQ8MEAwQDBANDw0PKRApECoPKg8pEAwQKRANDyoPDBAMEA0PKg8MEAwQDBANDwwQDBANDw0PDBAMEAwQDQ8MECkQKRAqDw0PDBAMEAwQDQ8NDwwQDBAMECoPKRApEA0PDQ8MEAwQDBANDw0PDBAMEA0PDQ8MEAwQDBANDw0PKRAMEAwQDQ8MEAwQDBAqDw0PDBAMDQ8QDQ8NDwwQDBAMEA0PDBAMEAwSDBAMEAwQKg8qDwwQKRAMEA0PDQ8MEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "20") %} "JgC8AXU3EAwQKRAMEA0PDQ8MEAwQDQ8NDwwQDBAMEA4OKRAMEAwQDQ8NDwwQDBAMECoPKg8pEAwQDBAqDw0PDBAMEAwQDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MECkQKRANDw0PDBAMEA0PAAFHdDcQDQ8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBApEA0PDQ8MEAwQDQ8NDwwQKRApECoPDQ8MECkQDBANDw0PDBAMEAwQDQ8MEAwQDBANDw0PDBApEAwQDQ8pECkQKRANDw0PDBAMEAwQKg8NDykQDA8NEA0PDQ8MEAwQDBANDwwQKRApECoPKg8pEAwOKxANDykQDBAMEA0PKg8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMECoPKg8pEAwQDBANDw0PDBAMEA0PDQ8MECkQKg8qDwwQDBAMEA0PDBAMEAwQDQ8NDwwQDBAMEAwQDQ8NDwwQKRAMEA0PDQ8MEAwQDBAqDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PDBAMEAwQKg8NDykQKRANDw0PDBAMEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "21") %} "JgC8AXU3EA0PKg8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQKRAMEA0PDQ8MEAwQDQ8NDykQKRAqDw0PDBApEAwQDQ8MEAwQDBANDw0PDBAMDQ8QDQ8NDwwQDBAMEA0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8NDykQKRAMEA0PDQ8MEAwQAAFGdTcQDQ8pEAwQDBANDw0PDBAMDg4QDQ8NDwwQDBApEA0PDBAMEAwQDQ8NDwwQKRApECoPDQ8MECkQDBANDw0PDBAMEAwQDQ8NDwwQDBANDw0PDBApEAwQDQ8qDykQKRAMEA0PDQ8pEAwQKRAMECkQDBANDwwQDBAMEA0PDQ8MEAwQKRAqDykQKRApEAwQKg8MECkQDBANDw0PKRAMEAwQDQ8NDwwQDBAMEA0PDBAMEAwQDQ8NDykQKRApEA0PDQ8MEAwQDBANDw0PDQ8NDykQKRApEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PKRAMEAwQDQ8NDw0PDBApEA0PDg8MEA0PDQ8MEAwQDBANDw0PDBAMEAwQDQ8MEAwQKRAqDykQKRAMEAwQDQ8MEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "22") %} "JgC8AXQ3EA0PKRAMEAwQDQ8NDwwQDA0PEA0PDQ8MEAwQKRANDwwQDBANDwwQDBAMECoPKg8pEAwQDBAqDwwQDBANDw0PDBAMDQ8QDQ8MEAwNDxANDw0PDBAMEAwQDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBANDyoPKRAMEAwQDQ8NDwwQAAFGdTcQDQ8qDwwQDBAMEA0PDQ8MEAwQDBANDwwRDA8qDwwQDBAMEA0PDQ8MEAwQKg8qDykQDBAMECoPDQ8MEAwQDBANDwwQDBAMEA0PDQ8MEAwQDBAqDwwQDBApECoPKg8MEAwQDBANDykQKRAMECoPDQ8MEAwPDRANDw0PDBAMEA0PKg8pECkQKRAqDw0PKRAMECoPDQ8MEAwQKRAMEA0PDBAMEAwQDQ8NDwwQDA0PEA0PDQ8NDykQKRApEA0PDQ8MEAwNDxANDw0PDBAMECkQKg8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBANDw0PDBAMEAwQKg8NDwwQDBAMEA0PDQ8pEAwPDRANDw0PDBAMDQ8QDQ8NDwwQDBAMEA0PDQ8MEAwQKRANDw0PDBApEA0PDQ8MEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "23") %} "JgC8AXQ3Dg4QKg8NDwwQDBANDw0PDBAMEAwQDQ8NDwwQKRAMEA0PDQ8MEAwQDBANDykQKRApEA0PDQ8pEAwNDxANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PDBAMEAwQDQ8NDwwQDA4OECoPKRAMEAwQDBANDw0PAAFGdTcQDBAqDw0PDBAMEAwQDQ8NDw0PDBAMEA0PDQ8pEAwQDBANDw0PDBAMEAwQKg8qDykQDBAMECoPDBAMEAwQDBANDw0PDBAMEAwQDQ8WDwwQEQwsEA0PDQ8pECkQKRANDwwQDBApECoPKRAMECkQDQ8MEAwQDBANDw0PDQ8NDwwQKRAqDykQKRApEAwQKg8MECkQDBANDw0PKRAMEAwQDQ8OEAwQDBANDw0PDBAMEAwQDQ8NDykQKRApEA0PDQ8MEAwQDQ8MEAwQDBANDyoPKRApEAwQDQ8NDwwQDA8NEAwQDQ8NDwwQDBAMEA0PDQ8MGQwQKg8NDwwQDBANDw0PDBApEAwQDQ8NDwwQEBAMEBEPDBANDw0PDBAMDg4QDQ8NDwwQKRApEA0PDQ8pEAwQDQ8NDwANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "24") %} "JgC8AXQ3EA0PKg8MEAwQDBANDw0PDBAMEA0PDQ8MEAwQKRANDw0PDBAMDQ8QDQ8NDykQKRAqDw0PDBApEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8NDw0PDQ8MEAwODhANDw0PDBAMEAwQDQ8NDwwQDBANDw0PDBAMECkQKg8NDwwQDBAMEA0PAAFGdTcQDBApEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PDQ8pEAwQDBANDw0PDBAMEAwQKg8pECkQDBAMECoPDQ8MEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDBAqDw0PDBApECkQKg8NDwwQDBAMEA0PDQ8pECkQDBANDw0PDBAMEAwQDQ8MEAwQKRAqDyoPKRApEAwQKg8NDykQDBANDw0PKRAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8MECkQKRAqDwwQDBAMEAwQDQ8MEAwQDBANDyoPKRApDg4QDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PKg8MEAwQDBANDw0PDBApEAwQDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PKg8MECkQDBAqDwwQDBAMEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "25") %} "JgC8AXU3Dg4QKg8NDwwQDQ8NDwwQDBAMEA0PDQ8MEAwQKRANDw0PDBAMEA0PDQ8MECkQKRAqDw0PDBApEAwQDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEA0PDQ8MEA0PDQ8MECkQKRANDw0PDQ8MEAwQAAFGdTcQDQ8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBApEA0PDBAMEAwQDQ8MEAwQKRApECoPDBAMECkQDQ8NDwwQDQ8NDw0PDBAMEA0PDQ8MEAwQDBAqDw0PDBApECkQKg8NDwwQDBApEA0PDBApECoPDQ8MEAwQDBANDw0PDBAMEAwQKg8qDykQKRApEA0PKRAMECkQDQ8NDw0PKRAMEAwQDQ8NDw0PDBAMEAwQDQ8NDwwQDBAMECoPKg8pEAwQDBANDw0PDBAMEAwQDQ8NDykQKRApEA0PDBAMEAwQDQ8NDwwQDBANDw0PDBAMEAwQDQ8NDwwQKRAMEA0PDBAMEAwQDQ8qDwwQDA4OEA0PDQ8MEAwQDBANDwwQDBAMEA0PDQ8NDwwQKRAqECkQDBApDQ8QDQ8NDwANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "26") %} "JgC8AXU4DwwQKRANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PKRAMEAwQDQ8NDwwQDA8NECoPKRApEAwQDBAqDw0PDBAMEAwQDQ8MEAwQDBANDw0PDBAMDQ8QDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDykQKRANDw0PDBAMEAwQAAFHdDQTDBApEAwQDQ8NDwwQDBANDw0PDBAMEAwQDQ8qDwwQDBANDw0PDBAMEA0PKg8pECkQDQ8NDykQDBAMEA0PDBAMEAwQDQ8NDwwQDBANDw0PDBApEA0PDQ8pECkQKRANDw0PDBAMECkQDQ8pECkQDBAMEA0PDQ8MEAwQDQ8NDwwQKQ0sECoPKRApEAwQKg8NDyoPDQ8MEAwQKRANDw0PDBANDw0PDBAMEAwQDQ8NDwwQDBAMECoPKg8pEAwPDRAMEAwQDQ8MEAwQDBANDyoPKRApEAwQDQ8NDwwQDBAMEA0PDQ8MEAwQDQ8NDwwQDBAMEA0PKRAMEAwQDBANDwwQDBApEA0PDQ8MEAwQDBANDw0PDBAMEA0PDQ8MEQ0PDQ8MEAwQKRANDwwQKRApEA0PDQ8MEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "27") %} "JgC8AXQ4Dw0PKRAMEAwQDQ8NDwwQDBAMEA0PDBAMEA4PKRAMEAwQDBANDwwQDBAMECkQKg8pEAwQDBAqDw0PDBAMEAwQDQ8NDwwQDBANDw0PDBAMEAwQDQ8NDwwRDBANDw0PDBAMEA0PDQ8MEAwQDBANDw0PDBAMECkQKg8MEAwQDBANDw0PAAFGdTcQDBApEA0PDBIMDwwQDA0PEA0PDQ8MEAwQDQ8qDwwQDBAMEA0PDQ8MEAwQKRAqDykQDBAMECoPDQ8MEAwQDBANDw0PDBENDw0PDBAMEA0PDQ8pEAwQDBApECoPKRAMEAwQDQ8qDykQDBApECoPDQ8MEAwODhANDw0PDBAMEAwQKg8pECkRKQ8qDw0PKRAMECkQDQ8NDwwQKRANDw0PDBAMDw0QDQ8NDwwQDBAMEA0PDBAMECoPKRApEAwQDQ8NDwwQDRAMDQ8QDQ8MECkQKRAqDwwQDBAMEA0PDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQKRANDw0PDBAMEAwQDQ8qDwwQDBANDw0PDBAMEAwQDQ8MEAwQDBANDw0PDBAMEAwQKg8qDwwQKRApEA0PDBAMEAANBQAAAAAAAAAAAAAAAA=="
          {% elif (selected_temp == "28") %} "JgC8AXQ3EAwQKg8NDwwQDBAMEA0PDQ8MEAwQDBANDw0PKRAMEA0PDQ8MEAwQDBANDyoPKRApEAwQDQ8pEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBINDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDBAMDg4QDBAMEAwQDQ8NDykQKQ0PEA0PDQ8NDwwQAAFGdTcQDQ8qDw0PDBAMEAwQDQ8NDwwQDBAMEA0PDQ8pEAwQDBANDw0PDBAMEA0PKg8pECkQDQ8NDykQDBAMEA0PDBANDw0PDBAMEAwQDQ8NDw0PDBApEAwQDQ8qDykQKRAMEAwQDBANDwwQKRApECoPDQ8MEAwQDQ8MEAwQDQ8MEA0PKg8pECkQKRAqDw0PKRAMECkQDQ8NDw0PKRAMEA0PDQ8NDwwQDBAMEA0PDQ8MEAwQDBANDykQKRApEA0PDg8MEAwQDBAMEA0PDQ8MECkQKRAqDwwQDBAMEA0PDQ8MEAwQDQ8MEAwNDxANDw0PDBAMEA0PKg8MEAwQDBANDw0PDBApEAwQDQ8MEAwQDBANDw0PDBAMEAwQDQ8NDwwQDBAMEA0PKRANDioQKg8pEAwQDBANDwANBQAAAAAAAAAAAAAAAA=="
          {% endif %}
```

**Comment by TomerFi** [comment]
You can also add another parameter to the `living_room_rm_pro_send_packet` script like `cmd` or something of the sort, and edit the script so that it checks the new parameter inside a `condition` and if the result is `ON` then it will send two packets, first the `ON` and then the one received from the previous scripts.
Of course you'll have to edit all the scripts and automation calling `living_room_rm_pro_send_packet` so that they'll pass the new parameter as well. But the upside will be that the `ON` packet will reside only inside the `living_room_rm_pro_send_packet` script.

**Comment by CloudHoang90** [comment]
Hi,
Sorry for late response!!

I just modify the automation script as below and it's work for my :). Really happy with that.
```
- id: lr_ac_status_on
  alias: lr_ac_status_on
  trigger:
    platform: state
    entity_id: input_boolean.lr_ac_status
    to: 'on'
  action:
    service: script.living_room_rm_pro_send_packet
    data:
      packet_code:
        - "power on IR code"
```
One more thing.. I think your code in README.md wrong some where
Because when I did extractly in  README.md, the UI in dashboard miss the MODE: HEAD+COOL and it don't work as I mentioned above.
I try to copy your full code and I work perfectly.

**Comment by TomerFi** [comment]
It's because we have different ac units,
mine doesn't have a `power on packet`.

I'm glad you got it working eventually.
👍
